owner: neo-ollie-deguzman
repo: db-orm-status

sites:
  - name: Google
    url: https://www.google.com
  - name: GitHub API
    url: https://api.github.com
    expectedStatusCodes:
      - 200
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  baseUrl: /db-orm-status
  name: "DB ORM Status"
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# See https://upptime.js.org/docs/configuration
